### ISSUE TITLE
heartrate missing for activities?

### ISSUE THREAD

**Issue by FlerioEU** [obalunenko/strava-api#57]
Hey :)

I am developing a small tool to analyze my activities. I noticed that this library does not provide heart rate data within the activity structs?

These are the related fields:

[GET /athlete/activities](https://developers.strava.com/docs/reference/#api-Activities-getLoggedInAthleteActivities)
```
{   
  "has_heartrate" : true,
  "average_heartrate" : 140.3,
  "max_heartrate" : 178
}
```

Is it possible to add them?

**Comment by obalunenko** [comment]
Hey, @FlerioEU !
Thank you for creating this issue and for your interest in this library.
Sure, I'll add these missed fields. But I'll be able to do that after 11 January
